MobilePhoneSearch/Models/ErrorViewModel.cs
using System;

namespace MobilePhoneSearch.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MobilePhoneSearch/Models/MobilePhones/MobilePhoneDetailViewModel.cs
using DataLayer.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MobilePhoneSearch.Models.MobilePhones
{
    public class MobilePhoneDetailViewModel
    {
        public int Id { get; set; }
        public string MobilePhoneName { get; set; }
        public string Size { get; set; }
        public int? Weight { get; set; }
        public decimal? ScreeenSize { get; set; }
        public string Resolution { get; set; }
        public string Processor { get; set; }
        public string Memory { get; set; }
        public string OperatingSystem { get; set; }
        public int? Price { get; set; }
        public string Video { get; set; }
        public List<Image> Images { get; set; }
        public Manufacturer Manufacturer { get; set; }

    }
}

MobilePhoneSearch/Models/MobilePhones/MobilePhoneListViewModel.cs
using BusinessLayer.Models;
using DataLayer.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MobilePhoneSearch.Models.MobilePhones
{
    public class MobilePhoneListViewModel
    {
        public MobilePhoneListFilterModel Filter { get; set; } = new MobilePhoneListFilterModel();
    }
}

MobilePhoneSearch/Controllers/MobilePhoneController.cs
using AutoMapper;
using BusinessLayer;
using BusinessLayer.Models.Shared;
using DataLayer.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MobilePhoneSearch.Helpers;
using MobilePhoneSearch.Models.MobilePhones;
using System.Collections.Generic;
using System.Linq;

namespace MobilePhoneSearch.Controllers
{
    public class MobilePhoneController : Controller
    {
        private IDataManager manager;
        private readonly IMapper _mapper;

        public MobilePhoneController(IDataManager manager, IMapper mapper)
        {
             this.manager = manager;
              _mapper = mapper;
        }
        [HttpGet]
        public IActionResult Index(MobilePhoneListViewModel model, PagingInfo paging)
        {
            var mobilephones = manager.Mobilephones.Get(model.Filter).AsQueryable();
            var manufacturers = Get();
            ViewBag.Manufacturers = manufacturers;
            var paged = new PaginatedList<MobilePhone>(mobilephones, paging);
            paging.SearchModel = model;
            return View(new BaseSearchModel<MobilePhoneListViewModel, PaginatedList<MobilePhone>>()
            {
                Search = model,
                DataModel = paged,
            });
        }
        [HttpGet]
        public IActionResult Details(int id)
        {
            if (id > 0)
            {
                var details = manager.Mobilephones.GetMobilehoneDetails(id);
                if (details != null)
                {
                    var model = _mapper.Map<MobilePhoneDetailViewModel>(details);
                    return View(model);
                }
            }
            return View(new MobilePhoneDetailViewModel());
        }
        [HttpGet]
        public List<SelectListItem> Get()
        {
            var result = new List<SelectListItem>();
            var manufacturers = manager.Manufacturers.Get();
            foreach (var item in manufacturers)
            {
                result.Add(new SelectListItem { Text = item.ManufacturerName.ToString(), Value = item.ManufacturerId.ToString() });
            }
            return result;
        }
    }
}

MobilePhoneSearch/Views/MobilePhone/Details.cshtml
@using MobilePhoneSearch.Models.MobilePhones

@model MobilePhoneDetailViewModel

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>


<div class="main_container">
    <div class="project_details_body">
        <div class="" style="align-content:center; align-items:center;">
            <div class="row">
                <div class="col-md-6 offset-3">
                    <div id="carouselExampleControls" class="carousel slide" style="width:600px; height:600px; align-content:center;" data-ride="carousel">
                        <div class="carousel-inner" style="width:600px; height:600px;">
                            @for (int i = 0; i < Model.Images.Count; i++)
                            {
                                var item = Model.Images[i];
                                if (i == 0)
                                {
                                    <div class="carousel-item active">
                                        <img src="@item.ImageUrl" class="d-block w-100" style="max-width:600px;width:600px; max-height:600px; height:600px;object-fit:cover " alt="...">
                                    </div>
                                }
                                else
                                {
                                    <div class="carousel-item">
                                        <img src="@item.ImageUrl" class="d-block w-100" style="max-width:600px;width:600px; max-height:600px; height:600px;object-fit:cover " alt="...">
                                    </div>
                                }
                            }
                        </div>
                        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                            <span class="carousel-control-prev-icon" style="background-color:darkseagreen;" aria-hidden="true"></span>
                            <span class="sr-only" style="color:darkseagreen;">Previous</span>
                        </a>
                        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                            <span class="carousel-control-next-icon" style="background-color:darkseagreen; " aria-hidden="true"></span>
                            <span class="sr-only" style="color:darkseagreen;">Next</span>
                        </a>
                    </div>
                </div>
            </div>

            <div class="details_desc">
                <div class="title">
                    <h1>@Model.MobilePhoneName</h1>
                </div>
                <div class="properties">
                    <div class="item">
                        <div class="name">ზომა</div>
                        <div class="value">@Model.Size</div>
                    </div>
                    <div class="item">
                        <div class="name">წონა</div>
                        <div class="value">@Model.Weight </div>
                    </div>
                    <div class="item">
                        <div class="name">ეკრანის ზომა</div>
                        <div class="value">@Model.ScreeenSize</div>
                    </div>
                    <div class="item">
                        <div class="name">რეზოლუცია</div>
                        <div class="value">@Model.Resolution</div>
                    </div>
                    <div class="item">
                        <div class="name">პროცესორი</div>
                        <div class="value">@Model.Processor </div>
                    </div>
                    <div class="item">
                        <div class="name">მეხსიერება</div>
                        <div class="value">@Model.Memory </div>
                    </div>
                    <div class="item">
                        <div class="name">ოპერატიუყლი სისტემა</div>
                        <div class="value">@Model.OperatingSystem </div>
                    </div>
                    <div class="item">
                        <div class="name">ფასი</div>
                        <div class="value">@Model.Price </div>
                    </div>
                    <div class="item">
                        <div class="name">ვიდეო</div>
                        <iframe width="420" height="315" src="@Model.Video" frameborder="0" allowfullscreen></iframe>
                    </div>
                    <div class="item">
                        <div class="name">მწარმოებელი</div>
                        <div class="value">@Model.Manufacturer.ManufacturerName </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

MobilePhoneSearch/Views/MobilePhone/Index.cshtml
@using BusinessLayer.Models.Shared;
@using BusinessLayer.Models;
@using MobilePhoneSearch.Helpers;
@using DataLayer.Models;
@using MobilePhoneSearch.Models.MobilePhones;

@model BaseSearchModel<MobilePhoneListViewModel, PaginatedList<MobilePhone>>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/css/bootstrap-select.min.css">
<link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
<div class="newcar-listing-section">
    <input type="hidden" class="seos" />
    <div class="container new-car-container">
        <div class="row">
            <div class="col-lg-3 col-12">
                <div class="list-filter new-car-list-filter">
                    <partial name="_ListFilter" model="Model.Search" />
                </div>
            </div>
            <div class="col-lg-9 col-12 pb-4">
                <div class="list-header d-flex justify-content-between align-items-center">
                    <h6>მობილურების რაოდენობა </h6>
                </div>
                <div class="filter-VSMId"></div>
                <div class="list-item-container">
                    <partial name="Partials/_ListingItems" />
                </div>
                <br />
                <div>
                    <nav aria-label="Page navigation example">
                        @Html.PageLinks(Model.DataModel.PagingInfo, Url.Action("Index", "MobilePhone"))
                    </nav>
                </div>
            </div>
        </div>
    </div>
</div>



@section Scripts{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/js/bootstrap-select.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
}

MobilePhoneSearch/Views/MobilePhone/Partials/_ListingItems.cshtml
@using BusinessLayer.Models.Shared;
@using BusinessLayer.Models;
@using MobilePhoneSearch.Helpers;
@using DataLayer.Models;
@using MobilePhoneSearch.Models.MobilePhones;

@model BaseSearchModel<MobilePhoneListViewModel, PaginatedList<MobilePhone>>

@{
        var manufacturers = (List<SelectListItem>)ViewBag.Manufacturers;
}

<div class="row w-100 ml-0">

    @if (Model.DataModel.Count() != 0)
    {
        @foreach (var px in Model.DataModel)
        {
            <div class="col-md-4 listing-item">
                <div class="item item-new-landing details-page-activities">
                    <a href="@Url.Action("Details","MobilePhone", new { id = px.Id})">
                        <div class="item-image" style="	background: linear-gradient(180deg, rgba(0,0,0,0) 41.21%, rgba(0,0,0,0.5) 100%), url(@px.Images.FirstOrDefault(x => x.IsMain == true).ImageUrl); height:200px">
                            <div class="category-title new-title">@manufacturers.FirstOrDefault().Value</div>
                        </div>
                    </a>
                    <a href="@Url.Action("Details","MobilePhone", new { id = px.Id})"><h4>@px.Name</h4></a>
                    <div class="item-bottom">
                        <div class="item-descr" style="padding: 0 5px;">@Html.Raw(px.Price)</div>
                    </div>
                </div>
            </div>
        }
    }
</div>

MobilePhoneSearch/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MobilePhoneSearch</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MobilePhoneSearch</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                @*<div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>*@
            </div>
        </nav>
    </header>
    <div class="container">
        @*<partial name="_CookieConsentPartial" />*@
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @*<footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - MobilePhoneSearch - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>*@

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

MobilePhoneSearch/Views/Shared/_ListFilter.cshtml
@using BusinessLayer.Models.Shared;
@using BusinessLayer.Models;
@using MobilePhoneSearch.Helpers
@using MobilePhoneSearch.Models.MobilePhones;

@model MobilePhoneListViewModel

@{
    var manufacturers = (List<SelectListItem>)ViewBag.Manufacturers;
}

<form asp-action="List" method="get" id="ListFilter">
    <div class="form-group">
        <h6>დასახელება</h6>
        <div class="d-flex justify-content-between filter-select-group">
            <div class="valute-changer mr-2">
                <input asp-for="Filter.MobileName" class="form-control pl-3 pr-0" />

            </div>
        </div>
    </div>
    <div class="form-group">
        <select asp-for="Filter.ManufacturerId" asp-items="manufacturers" id="districtId" data-live-search="true" class="form-control district selectpicker">
            <option value="0">გთხოვთ აირჩიოთ</option>
        </select>
    </div>
    <div class="form-group">
        <h6>ფასი</h6>
        <div class="d-flex justify-content-between filter-select-group">
            <input asp-for="Filter.PriceFrom" class="form-control" placeholder="დან" />
            <input asp-for="Filter.PriceTo" class="form-control" placeholder="მდე" />
        </div>
    </div>
    <div class="fixed-section">
        <button class="btn btn-primary searchBtn mt-3">განხცადებების ძებნა</button>
    </div>

</form>